# Generated by Django 5.2.7 on 2025-10-04 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('Hause', 'Dom'), ('Siłownia', 'Siłownia')], default='Hause', max_length=30)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)])),
                ('libra', models.IntegerField(validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(350)])),
                ('n_exercise', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('objective', models.CharField(choices=[('Redukcja tkanki tłuszczowej i utrata wagi', 'Redukcja Tkanki Tłuszczowej I Utrata Wagi'), ('Budowanie masy mięśniowej', 'Budowanie Masy Mięśniowej'), ('Poprawa jakości mięśni', 'Poprawa Jakości Mięśni'), ('Zwiększenie wydolności', 'Zwiększenie Wydolności'), ('Poprawa elastyczności i ruchomości', 'Poprawa Elastyczności I Ruchomości'), ('Poprawa zdrowia układu krążenia', 'Zdrowie'), ('Korekcja wad postawy', 'Korekcja Wad Postawy'), ('Relaksacja i redukcja stresu', 'Relaksacja I Redukcja Stresu'), ('Poprawa samopoczucia', 'Poprawa Samopoczucia')], default='Redukcja tkanki tłuszczowej i utrata wagi', max_length=100)),
            ],
        ),
    ]
