# Generated by Django 5.2.7 on 2025-10-05 01:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DieatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.CharField(blank=True, max_length=300)),
                ('food', models.CharField(max_length=300)),
                ('food_not_like', models.CharField(blank=True, max_length=300)),
                ('intention', models.CharField(choices=[('Redukcja masy ciała', 'Redukcja Masy Ciała'), ('Budowanie masy mięśniowej', 'Budowanie Masy Mięśniowej'), ('Ogólny dobrostan', 'Ogólny Dobrostan')], default='Redukcja masy ciała', max_length=100)),
                ('diet_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
